#import "../problemst/pset.typ": pset, framed

#show: pset.with(
  class: "07112303",
  student: "左逸龙",
  title: "计算机网络第6章作业",
  date: datetime.today()
)

= The Wireshark capture below shows a hex stream of an Ethernet frame generated by an application.

#block(
  fill: luma(240),
  inset: 8pt,
  radius: 4pt,
  width: 100%,
)[
  #set text(font: "Courier New", size: 9pt)
  34c93d1de1e7f033e57acfed0800450000347bc740007d0645090a0006ca0a3e21ec01bb0dcd7e82 04765806bbc480120839838e0000020405b40103030201010402
]

*Examine the frame and answer the following questions:*

== What are the source and destination MAC addresses (in Hex)?

#framed[
  Ethernet 帧前 $6$ 字节是目的 MAC，接着 $6$ 字节是源 MAC。

  因此源 MAC 地址为 `f0:33:e5:7a:cf:ed`，目的 MAC 地址为 `34:c9:3d:1d:e1:e7`。
]

== What are the source and destination IP addresses (in dotted decimal)?

#framed[
  IP 首部中源 IP 字段为 `0a 00 06 ca`，目的 IP 字段为 `0a 3e 21 ec`。

  转换成点分十进制后，源 IP 地址为 $10.0.6.202$，目的 IP 地址为 $10.62.33.236$。
]

== What protocol type is the payload carried by IP packets?

#framed[
  IP 首部中的 Protocol 字段为 `06`，因此 IP 分组承载的上层协议是 TCP。
]

== What is the source port number? How would you classify the source port?

#framed[
  TCP 首部前两个字节为源端口，即 `01 bb`。

  `0x01bb` 转成十进制为 $443$，所以源端口号为 $443$，属于 well-known port，通常对应 HTTPS 服务。
]

== What is the destination port number? How would you classify the destination port?

#framed[
  TCP 首部接下来的两个字节为目的端口，即 `0d cd`。

  `0x0dcd` 转成十进制为 $3533$，所以目的端口号为 $3533$，它不是 well-known port，可看作客户端使用的临时端口。
]

= You are hired to design a reliable byte-stream protocol that uses a sliding window (like TCP). This protocol will run over a 1-Gbps network. The RTT of the network is 100 ms, and the maximum segment lifetime is 30 seconds. How many bits would you include in the *AdvertisedWindow* and *SequenceNum* fields of your protocol header?

#framed[
  AdvertisedWindow 至少要能表示带宽时延积。

  $1 "Gbps" times 100 "ms" = 10^9 times 0.1 = 10^8 "bits" = 12.5 times 10^6 "B"$

  由于 $2^23 < 12.5 times 10^6 < 2^24$，所以 AdvertisedWindow 字段至少需要 $24$ bit。

  SequenceNum 按字节编号，要求在 $30$ 秒 MSL 内不能回绕。

  $1 "Gbps" times 30 "s" = 30 times 10^9 "bits" = 3.75 times 10^9 "B"$

  由于 $2^31 < 3.75 times 10^9 < 2^32$，所以 SequenceNum 字段至少需要 $32$ bit。
]

= Consider @fig:6-1. Assuming TCP Reno is the protocol experiencing the behavior shown above, answer the following questions. In all cases, you should provide a short discussion justifying your answer.

#figure(
  image("attachments/fig6.1.jpg", width: 60%),
  caption: [TCP congestion window size],
) <fig:6-1>

== Identify the intervals of time when TCP slow start is operating.

#framed[
  慢启动阶段窗口按指数增长。

  从图中可看出第 $1$ 到 $6$ 轮窗口为 $1,2,4,8,16,32$，所以第 $1$ 到 $6$ 轮是慢启动。

  第 $23$ 轮超时后窗口重新变为 $1$，之后第 $23$ 到 $26$ 轮也是慢启动。
]

== Identify the intervals of time when TCP congestion avoidance is operating.

#framed[
  拥塞避免阶段窗口大致每轮线性增加 $1$。

  图中第 $6$ 到 $16$ 轮，以及第 $17$ 到 $22$ 轮为拥塞避免阶段。
]

== After the 16th transmission round, is segment loss detected by a triple duplicate ACK or by a timeout?

#framed[
  第 $16$ 轮后窗口从约 $42$ 降到 $24$，没有降到 $1$。

  因此这是通过 triple duplicate ACK 检测到丢包。
]

== After the 22nd transmission round, is segment loss detected by a triple duplicate ACK or by a timeout?

#framed[
  第 $22$ 轮后窗口直接降到 $1$。

  因此这是通过 timeout 检测到丢包。
]

== What is the initial value of ssthresh at the first transmission round?

#framed[
  开始时窗口一直指数增长到 $32$，之后转为线性增长。

  因此初始的 $s s t h r e s h$ 为 $32$。
]

== What is the value of ssthresh at the 18th transmission round?

#framed[
  第 $16$ 轮发生丢包时，拥塞窗口约为 $42$。

  Reno 将 $s s t h r e s h$ 设为窗口的一半，所以第 $18$ 轮时 $s s t h r e s h = 42 / 2 = 21$。
]

== What is the value of ssthresh at the 24th transmission round?

#framed[
  第 $22$ 轮发生 timeout 时，拥塞窗口约为 $29$。

  因此新的 $s s t h r e s h = 29 / 2 approx 14$。
]

== During what transmission round is the 70th segment sent?

#framed[
  前 $6$ 轮共发送
  $1 + 2 + 4 + 8 + 16 + 32 = 63$
  个 segment。

  所以第 $70$ 个 segment 会在第 $7$ 轮发送。
]

== Assuming a packet loss is detected after the 26th round by the receipt of a triple duplicate ACK, what will be the values of the congestion window size and of ssthresh ?

#framed[
  第 $26$ 轮时拥塞窗口为 $8$。

  收到 triple duplicate ACK 后，$s s t h r e s h = 8 / 2 = 4$。

  Reno 快速恢复时，拥塞窗口变为 $s s t h r e s h + 3 = 7$。
]

== Suppose TCP Tahoe is used (instead of TCP Reno), and assume that triple duplicate ACKs are received at the 16th round. What are the ssthresh and the congestion window size at the 19th round?

#framed[
  Tahoe 收到 triple duplicate ACK 后也会把 $s s t h r e s h$ 设为原窗口一半，即 $42 / 2 = 21$。

  但 Tahoe 会把拥塞窗口降为 $1$ 并重新慢启动。

  因此第 $17,18,19$ 轮窗口分别为 $1,2,4$，所以第 $19$ 轮 $s s t h r e s h=21$，拥塞窗口为 $4$。
]

== Again suppose TCP Tahoe is used, and there is a timeout event at 22nd round. How many packets have been sent out from 17th round till 22nd round, inclusive.

#framed[
  按 Tahoe，前面第 $16$ 轮后重新慢启动，且 $s s t h r e s h=21$。

  第 $17$ 到 $22$ 轮发送的分组数分别为 $1,2,4,8,16,21$。

  所以总数为
  $1 + 2 + 4 + 8 + 16 + 21 = 52$。
]

= Assume that TCP implements an extension that allows window sizes much larger than 64 KB. Suppose that you are using this extended TCP over a 1-Gbps link with a latency of 50 ms to transfer a 10-MB file, and the TCP receive window is 1 MB. If TCP sends 1-KB packets (assuming no congestion and no lost packets):

== How many RTTs does it take until slow start opens the send window to 1 MB?

#framed[
  每个分组大小为 $1 "KB"$，接收窗口为 $1 "MB"$，即窗口最多为 $1024$ 个分组。

  慢启动中窗口每个 RTT 翻倍：
  $1,2,4,...,1024$

  由于 $2^10 = 1024$，所以需要 $10$ 个 RTT 才能把发送窗口打开到 $1 "MB"$。
]

== How many RTTs does it take to send the file?

#framed[
  文件大小为 $10 "MB"$，即 $10240$ 个 $1 "KB"$ 分组。

  前 $10$ 个 RTT 中发送的分组数为
  $1 + 2 + ... + 512 = 1023$。

  剩余 $10240 - 1023 = 9217$ 个分组。

  此后窗口为 $1024$ 个分组，每 RTT 最多发送 $1024$ 个分组，所以还需要
  $ceil(9217 / 1024) = 10$
  个 RTT。

  因此总共需要 $20$ 个 RTT。
]

== If the time to send the file is given by the number of required RTTs multiplied by the link latency, what is the effective throughput for the transfer? What percentage of the link bandwidth is utilized?

#framed[
  传输时间为
  $20 times 50 "ms" = 1 "s"$。

  $10 "MB" = 10 times 1024 times 1024 times 8 "bits" approx 83.9 "Mbits"$。

  因此有效吞吐率约为 $83.9 "Mbps"$。

  链路带宽为 $1 "Gbps"$，所以利用率约为
  $83.9 / 1000 = 8.39%$。
]
